# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

env:
  AUTOMATE_CORE: ${{ github.workspace }}/core

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #  run: deno fmt --check

      # - name: Run linter
      #  run: deno lint

      - name: Print env
        run: printenv | sort

      - name: Run `automate.core` tests
        run: deno task test-core

      - name: Run `test.workspace.example` tests
        run: deno task cli-test-test-workspace

      - name: Build `test.workspace.example` packages
        run: deno task cli-build-test-workspace

      - name: Install `automate` cli and call `automate --help`
        run: deno task install-cli && automate --help

      - name: Run `automate provider list`
        run: automate provider list

      - name: Run `automate provider show`
        run: automate provider show provider.test.workspace.example.name1@0.0.0

      - name: Run `automate provider run`
        run: automate provider run provider.test.workspace.example.name1@0.0.0

      - name: Run `automate recipe run`
        run: automate recipe run recipe.test.workspace.example.name1@0.0.0
